services:
  - name: flask-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT app.py:app

  - name: nextjs-frontend
    env: node
    buildCommand: |
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production