services:
  - name: flask-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: web
    name: nextjs
    env: node
    buildCommand: |
      yarn; yarn build
    startCommand: yarn start
